name: n_image_picker
description: Configurable and easy-to-use cross-platform image selector.
version: 1.1.0

homepage: https://github.com/nycm1989/nImagePicker
repository: https://github.com/nycm1989/nImagePicker

topics:
  - picker
  - image
  - preview
  - cross-platform

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.3.0'


dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  http: ^1.2.0
  http_parser: ^4.0.2
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: 'Loaded image screenshot'
    path: screens/2.png

# dart pub publish --dry-run